# Generated by Django 5.1.4 on 2025-02-09 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TV', 'Television'), ('Social Media', 'Social Networks'), ('Radio', 'Radio'), ('Search Engine', 'Search Engines')], max_length=50)),
                ('type', models.CharField(choices=[('TV', 'Television'), ('Social Media', 'Social Networks'), ('Radio', 'Radio'), ('Search Engine', 'Search Engines')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('channels', models.ManyToManyField(to='campaigns.channel')),
            ],
        ),
    ]
