from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CampaignViewSet

# Create a router and register the CampaignViewSet
router = DefaultRouter()
router.register(r'campaigns', CampaignViewSet)  # URL endpoint for 'campaigns' will map to CampaignViewSet

urlpatterns = [
    path('api/', include(router.urls)),  # All the URLs generated by the router will be included
]
