from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CampaignViewSet
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

# Create a router and register the CampaignViewSet
router = DefaultRouter()
router.register(r'campaigns', CampaignViewSet)  # URL endpoint for 'campaigns' will map to CampaignViewSet

urlpatterns = [
    # Include JWT endpoints
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/', include(router.urls)),  # All the URLs generated by the router will be included
]
